main: trigger PTP start/stop from wrpc, remove old/wrong prototype
Trigger start/stop of PTP from wrc_check_link job instead of PTP's job.
This picks ppsi's new master that matches the change.

We need to remove prototype for an unused function, now that the one
in ppsi changed arguments and we'd otherwise get

  error: conflicting types for 'wr_servo_reset'

Signed-off-by: Adam Wujek <adam.wujek@cern.ch>
Signed-off-by: Alessandro Rubini <a.rubini@gsi.de>