config: cmd_diag depends on wr_node
We'd miss some symbols in wrs, besides missing the shell

   shell/cmd_diag.c:32:30: error: 'DIAG_RO_BANK' undeclared

(thanks randconfig)

Signed-off-by: Alessandro Rubini <rubini@gnudd.com>